In [2]:
#1. Using Python Lists
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]

C = [[0, 0], [0, 0]]

for i in range(2):
    for j in range(2):
        C[i][j] = A[i][j] + B[i][j]

print("First Matrix:")
print(A)

print("Second Matrix:")
print(B)

print("Addition of two matrices:")
print(C)

First Matrix:
[[1, 2], [3, 4]]
Second Matrix:
[[5, 6], [7, 8]]
Addition of two matrices:
[[6, 8], [10, 12]]


In [1]:
#2. Using NumPy Array

import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A + B

print("First Matrix:")
print(A)

print("Second Matrix:")
print(B)

print("Addition of two matrices:")
print(C)

First Matrix:
[[1 2]
 [3 4]]
Second Matrix:
[[5 6]
 [7 8]]
Addition of two matrices:
[[ 6  8]
 [10 12]]
